olist_store:
  outputs:
    dev:
      dbname: airflow
      host: localhost
      pass: airflow
      port: 5433
      schema: transforms
      threads: 1
      type: postgres
      user: airflow
  target: dev
